platformName=Android
deviceName=emulator-5554
automationName=UiAutomator2
appPackage=com.cleartrip.android
appActivity=com.cleartrip.android.common.activities.CleartripHomeActivity
appiumServer=http://127.0.0.1:4723
# added for git tracking